# Generated by Django 5.1 on 2024-08-22 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2000)),
                ('language', models.CharField(max_length=100)),
                ('submission_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('s', 'Success'), ('P', 'Pending'), ('E', 'Error')], max_length=1)),
                ('user_input', models.CharField(blank=True, max_length=200, null=True)),
                ('output', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
